name: statitikcard
description: Logiciel de partage de tirage et visualisation des statistiques pour Pokémon JCC.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+249

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  firebase_core: ^1.16.0
  firebase_auth_web: ^3.3.14
  firebase_auth: ^3.3.17
  provider: ^6.0.0
  mysql1: ^0.19.2
  cached_network_image: ^3.2.0
  google_sign_in: ^5.0.5
  percent_indicator: ^4.2.0
  fl_chart: ^0.50.1
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.8
  sprintf: ^6.0.0
  flutter_spinbox: ^0.8.0
  permission_handler: ^8.2.2
  path_provider: ^2.0.2
  photo_manager: ^2.1.1
  screenshot: ^1.2.3
  carousel_slider: ^4.0.0
  kana_kit: ^2.0.0
  flutter_easyloading: ^3.0.3
  http: ^0.13.4
  flutter_image_compress: ^1.1.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: any
  flutter_launcher_icons: "^0.9.0"

# Run I:\Programmation\Android\flutter\bin\flutter.bat pub run flutter_launcher_icons:main
flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/statitikIconIOS.png"
  image_path_android: "assets/statitikIconAndroid.png"
  adaptive_icon_background: "assets/background3.png"
  adaptive_icon_foreground: "assets/statitikIcon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/langue/france.png
    - assets/langue/usa.png
    - assets/langue/japon.png
    - assets/carte/alternative.png
    - assets/carte/set_standard.png
    - assets/carte/set_parallel.png
    - assets/carte/set_holo.png
    - assets/carte/set_TG.png
    - assets/carte/set_25.png
    - assets/carte/set_energy.png
    - assets/carte/set_other.png
    - assets/carte/set_Promo.png
    - assets/design/ArtNormal.png
    - assets/design/ArtHalf.png
    - assets/design/ArtFull.png
    - assets/energie/plante.png
    - assets/energie/feu.png
    - assets/energie/electrique.png
    - assets/energie/eau.png
    - assets/energie/fee.png
    - assets/energie/dragon.png
    - assets/energie/incolore.png
    - assets/energie/metal.png
    - assets/energie/obscure.png
    - assets/energie/combat.png
    - assets/energie/psy.png
    - assets/arrowR.png
    - assets/arrowL.png
    - assets/logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: StatitikFont
      fonts:
        - asset: fonts/StatitikFont.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
