/// Flutter icons StatitikFont
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  StatitikFont
///      fonts:
///       - asset: fonts/StatitikFont.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class StatitikFont {
  StatitikFont._();

  static const _kFontFam = 'StatitikFont';
  static const String? _kFontPkg = null;

  static const IconData font_01_pokecard = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData font_02_pioche = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData font_03_coin = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData font_04_burn = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData font_05_poison = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData font_06_paralized = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData font_07_sleep = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData font_08_search = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData font_09_attack = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData font_10_mix = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData font_11_confusion = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData font_12_heal = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
