/// Flutter icons StatitikFont
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  StatitikFont
///      fonts:
///       - asset: fonts/StatitikFont.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class StatitikFont {
  StatitikFont._();

  static const _kFontFam = 'StatitikFont';
  static const String? _kFontPkg = null;

  static const IconData font01Pokecard = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData font02Pioche = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData font03Coin = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData font04Burn = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData font05Poison = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData font06Paralized = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData font07Sleep = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData font08Search = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData font09Attack = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData font10Mix = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData font11Confusion = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData font12Heal = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
